version: '3'

services:
  organisation-app:
    container_name: co-cdp-organisation-app
    build:
      context: Frontend/CO.CDP.OrganisationApp
      dockerfile: Dockerfile
      target: final
    image: 'cabinetoffice/cdp-organisation-app:${IMAGE_VERSION:-latest}'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  tenant:
    container_name: co-cdp-tenant
    build:
      context: Services/Tenant
      dockerfile: Dockerfile
      target: final
    image: 'cabinetoffice/cdp-tenant:${IMAGE_VERSION:-latest}'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  organisation:
    container_name: co-cdp-organisation
    build:
      context: Services/Organisation
      dockerfile: Dockerfile
      target: final
    image: 'cabinetoffice/cdp-organisation:${IMAGE_VERSION:-latest}'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  person:
    container_name: co-cdp-person
    build:
      context: Services/Person
      dockerfile: Dockerfile
      target: final
    image: 'cabinetoffice/cdp-person:${IMAGE_VERSION:-latest}'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  forms:
    container_name: co-cdp-forms
    build:
      context: Services/Forms
      dockerfile: Dockerfile
      target: final
    image: 'cabinetoffice/cdp-forms:${IMAGE_VERSION:-latest}'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  data-sharing:
    container_name: co-cdp-data-sharing
    build:
      context: Services/DataSharing
      dockerfile: Dockerfile
      target: final
    image: 'cabinetoffice/cdp-data-sharing:${IMAGE_VERSION:-latest}'
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10
