services:
  gateway:
    container_name: co-cdp-gateway
    image: nginx:1.27
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  db:
    container_name: co-cdp-db
    image: postgres:16.2
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U$${POSTGRES_USER:-} -d $${POSTGRES_DB:-}" ]
      interval: 3s
      timeout: 5s
      retries: 5

  localstack:
    container_name: co-cdp-localstack
    image: localstack/localstack:3.5
    healthcheck:
      test: [ "CMD-SHELL", "bash", "-c", "awslocal sqs list-queues && awslocal s3 ls"]

  organisation-information-migrations:
    container_name: co-cdp-organisation-information-migrations
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations-organisation-information
    image: 'cabinetoffice/cdp-organisation-information-migrations:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  organisation-app:
    container_name: co-cdp-organisation-app
    build:
      context: .
      dockerfile: Dockerfile
      target: final-organisation-app
    image: 'cabinetoffice/cdp-organisation-app:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  authority:
    container_name: co-cdp-authority
    build:
      context: .
      dockerfile: Dockerfile
      target: final-authority
    image: 'cabinetoffice/cdp-authority:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  tenant:
    container_name: co-cdp-tenant
    build:
      context: .
      dockerfile: Dockerfile
      target: final-tenant
    image: 'cabinetoffice/cdp-tenant:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  organisation:
    container_name: co-cdp-organisation
    build:
      context: .
      dockerfile: Dockerfile
      target: final-organisation
    image: 'cabinetoffice/cdp-organisation:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  person:
    container_name: co-cdp-person
    build:
      context: .
      dockerfile: Dockerfile
      target: final-person
    image: 'cabinetoffice/cdp-person:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  forms:
    container_name: co-cdp-forms
    build:
      context: .
      dockerfile: Dockerfile
      target: final-forms
    image: 'cabinetoffice/cdp-forms:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  data-sharing:
    container_name: co-cdp-data-sharing
    build:
      context: .
      dockerfile: Dockerfile
      target: final-data-sharing
    image: 'cabinetoffice/cdp-data-sharing:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10

  entity-verification:
    container_name: co-cdp-entity-verification
    build:
      context: .
      dockerfile: Dockerfile
      target: final-entity-verification
    image: 'cabinetoffice/cdp-entity-verification:${IMAGE_VERSION:-latest}'
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10