version: '3'

services:
  tenant:
    container_name: co-org-info-tenant
    build:
      context: Tenant
      dockerfile: Dockerfile
      target: final
    image: 'cabinetoffice/org-info-tenant:${IMAGE_VERSION:-latest}'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out '{\"status\":%{http_code}}' --output /dev/null http://127.0.0.1:8080/health"]
      start_period: 10s
      interval: 60s
      timeout: 10s
      retries: 10
