{
 "title": "WAF - Summary",
 "tags": [
  "external",
  "summary",
  "traffic",
  "waf"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "action_filter", "label": "WAF Action", "query": "ALLOW,BLOCK,COUNT" },
   {
    "name": "web_acl",
    "label": "Web ACL",
    "query": "cdp-sirsi-acl,cdp-sirsi-php-acl,cdp-sirsi-fts-acl,cdp-sirsi-tools-acl"
   },
   {
    "name": "waf_log_group",
    "label": "WAF Log Group",
    "query": "aws-waf-logs-cdp-sirsi,aws-waf-logs-cdp-sirsi-php,aws-waf-logs-cdp-sirsi-fts,aws-waf-logs-cdp-sirsi-tools"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Countries (all actions)",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-php:*",
       "name": "aws-waf-logs-cdp-sirsi-php"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-fts:*",
       "name": "aws-waf-logs-cdp-sirsi-fts"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-tools:*",
       "name": "aws-waf-logs-cdp-sirsi-tools"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "expression": "fields @timestamp\n| parse @message /\"webaclId\":\"(?<webaclId>[^\"]+)\"/\n| filter @log like /$waf_log_group/\n| parse @message /\"country\":\"(?<country>[^\"]+)\"/\n| parse @message /\"action\":\"(?<action>[^\"]+)\"/\n| filter webaclId like /$web_acl/\n| filter action like /$action_filter/\n| stats count() as requests by country, action\n| sort requests desc",
     "queryLanguage": "CWLI",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Client IPs (all actions)",
   "type": "table",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-php:*",
       "name": "aws-waf-logs-cdp-sirsi-php"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-fts:*",
       "name": "aws-waf-logs-cdp-sirsi-fts"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-tools:*",
       "name": "aws-waf-logs-cdp-sirsi-tools"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "expression": "fields @timestamp\n| parse @message /\"webaclId\":\"(?<webaclId>[^\"]+)\"/\n| filter @log like /$waf_log_group/\n| parse @message /\"clientIp\":\"(?<ip>[^\"]+)\"/\n| parse @message /\"action\":\"(?<action>[^\"]+)\"/\n| filter webaclId like /$web_acl/\n| filter action like /$action_filter/\n| stats count() as requests by ip, action\n| sort requests desc",
     "queryLanguage": "CWLI",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top URIs (all actions)",
   "type": "table",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-php:*",
       "name": "aws-waf-logs-cdp-sirsi-php"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-fts:*",
       "name": "aws-waf-logs-cdp-sirsi-fts"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-tools:*",
       "name": "aws-waf-logs-cdp-sirsi-tools"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "expression": "fields @timestamp\n| parse @message /\"webaclId\":\"(?<webaclId>[^\"]+)\"/\n| filter @log like /$waf_log_group/\n| parse @message /\"uri\":\"(?<uri>[^\"]+)\"/\n| parse @message /\"action\":\"(?<action>[^\"]+)\"/\n| filter webaclId like /$web_acl/\n| filter action like /$action_filter/\n| stats count() as requests by uri, action\n| sort requests desc",
     "queryLanguage": "CWLI",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Methods (all actions)",
   "type": "table",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-php:*",
       "name": "aws-waf-logs-cdp-sirsi-php"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-fts:*",
       "name": "aws-waf-logs-cdp-sirsi-fts"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-tools:*",
       "name": "aws-waf-logs-cdp-sirsi-tools"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "expression": "fields @timestamp\n| parse @message /\"webaclId\":\"(?<webaclId>[^\"]+)\"/\n| filter @log like /$waf_log_group/\n| parse @message /\"httpMethod\":\"(?<method>[^\"]+)\"/\n| parse @message /\"action\":\"(?<action>[^\"]+)\"/\n| filter webaclId like /$web_acl/\n| filter action like /$action_filter/\n| stats count() as requests by method, action\n| sort requests desc",
     "queryLanguage": "CWLI",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top User Agents (all actions)",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-php:*",
       "name": "aws-waf-logs-cdp-sirsi-php"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-fts:*",
       "name": "aws-waf-logs-cdp-sirsi-fts"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-tools:*",
       "name": "aws-waf-logs-cdp-sirsi-tools"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "expression": "fields @timestamp\n| parse @message /\"webaclId\":\"(?<webaclId>[^\"]+)\"/\n| filter @log like /$waf_log_group/\n| parse @message /\"name\":\"User-Agent\",\"value\":\"(?<ua>[^\"]+)\"/\n| parse @message /\"action\":\"(?<action>[^\"]+)\"/\n| filter webaclId like /$web_acl/\n| filter action like /$action_filter/\n| stats count() as requests by ua, action\n| sort requests desc",
     "queryLanguage": "CWLI",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top WAF Rules (by action)",
   "type": "table",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-php:*",
       "name": "aws-waf-logs-cdp-sirsi-php"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-fts:*",
       "name": "aws-waf-logs-cdp-sirsi-fts"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi-tools:*",
       "name": "aws-waf-logs-cdp-sirsi-tools"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "expression": "fields @timestamp\n| parse @message /\"webaclId\":\"(?<webaclId>[^\"]+)\"/\n| filter @log like /$waf_log_group/\n| parse @message /\"action\":\"(?<action>[^\"]+)\"/\n| parse @message /\"terminatingRuleId\":\"(?<terminatingRuleId>[^\"]+)\"/\n| filter webaclId like /$web_acl/\n| filter action like /$action_filter/\n| stats count() as hits by action, terminatingRuleId\n| sort hits desc",
     "queryLanguage": "CWLI",
     "statistic": "Average"
    }
   ]
  }
 ]
}