{
 "title": "RDS Performance Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "DB",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$db", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "db" },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Helps determine if the instance type is appropriate for the workload",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$db" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "description": "Helps in assessing disk I/O performance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$db" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "description": "Monitor memory usage to check if the instance is under or over-provisioned.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$db" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Read/Write Latency",
   "type": "timeseries",
   "description": "Monitors the time it takes to complete read/write operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$db" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "$db" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "description": "Ensures the instance can handle the number of concurrent connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$db" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "description": "Ensures you have sufficient storage and can help in planning storage scaling",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$db" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}