{
 "title": "SQS Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "Queue",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "queue",
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Empty Receives",
     "type": "timeseries",
     "description": "The number of ReceiveMessage API calls that did not return a message. Reporting criteria: A non-negative value is reported if the queue is active.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "dimensions": { "QueueName": "$queue" },
       "metricName": "NumberOfEmptyReceives",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Number Of Messages Deleted",
     "type": "timeseries",
     "description": "The number of messages deleted from the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "dimensions": { "QueueName": "$queue" },
       "metricName": "NumberOfMessagesDeleted",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Number Of Messages Received",
     "type": "timeseries",
     "description": "The number of messages returned by calls to the <code>ReceiveMessage</code> action. Reporting criteria: A non-negative value is reported <a href=\"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/monitoring-using-cloudwatch.html\">if the queue is active</a>.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "dimensions": { "QueueName": "$queue" },
       "metricName": "NumberOfMessagesReceived",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Number Of Messages Sent",
     "type": "timeseries",
     "description": "The number of messages added to a queue. If you send a message to a DLQ manually, it is captured by the <code>NumberOfMessagesSent</code> metric. However, if a message is sent to a DLQ as a result of a failed processing attempt (for example, automatically moved due to exceeding the <code>maxReceiveCount</code>), it is not captured by this metric. Therefore, it is possible for the values of <code>NumberOfMessagesSent</code> and <code>NumberOfMessagesReceived</code> to differ. Reporting criteria: A non-negative value is reported <a href=\"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/monitoring-using-cloudwatch.html\">if the queue is active</a>.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "dimensions": { "QueueName": "$queue" },
       "metricName": "NumberOfMessagesSent",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Sent Message Size",
     "type": "timeseries",
     "description": "The size of messages added to a queue. Reporting criteria: A non-negative value is reported <a href=\"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/monitoring-using-cloudwatch.html\">if the queue is active</a>. Note: <code>SentMessageSize</code> does not display as an available metric in the CloudWatch console until at least one message is sent to the corresponding queue.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "QueueName": "$queue" },
       "metricName": "SentMessageSize",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Number Of Deduplicated Sent Messages ",
     "type": "timeseries",
     "description": "The number of messages sent to a queue that were deduplicated. This metric can help determine if a producer is sending duplicate messages to an Amazon SQS FIFO queue. Reporting criteria: A non-negative value is reported <a href=\"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/monitoring-using-cloudwatch.html\">if the queue is active</a>.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "count" } },
     "targets": [
      {
       "dimensions": { "QueueName": "$queue" },
       "metricName": "NumberOfDeduplicatedSentMessages",
       "namespace": "AWS/SQS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}