{
 "title": "WAF Overview",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Blocked",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "ManagedRuleGroup": "*", "Region": "eu-west-2", "WebACL": "cdp-sirsi-acl" },
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "limit": 10,
      "orderBy": { "name": "COUNT", "type": "function" },
      "orderByDirection": "DESC",
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "BlockedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(BlockedRequests) FROM \"AWS/WAFV2\" GROUP BY Rule ORDER BY COUNT() DESC LIMIT 10",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "dimensions": { "ManagedRuleGroup": "*", "Region": "eu-west-2", "WebACL": "cdp-sirsi-acl" },
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "BlockedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(BlockedRequests) FROM \"AWS/WAFV2\"",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Observed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "dimensions": { "Region": "eu-west-2", "Rule": "*", "WebACL": "cdp-sirsi-acl" },
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "limit": 10,
      "orderBy": { "name": "COUNT", "type": "function" },
      "orderByDirection": "DESC",
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "BlockedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(BlockedRequests) FROM \"AWS/WAFV2\" GROUP BY Rule ORDER BY COUNT() DESC LIMIT 10",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "dimensions": { "Region": "eu-west-2", "Rule": "*", "WebACL": "cdp-sirsi-acl" },
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "BlockedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT COUNT(BlockedRequests) FROM \"AWS/WAFV2\"",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Last 100 Blocked",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
   "targets": [
    {
     "expression": "fields @timestamp, action as `Action`, labels.0.name as `Rule`, httpRequest.clientIp as `Client IP`, httpRequest.country as `Country`, httpRequest.uri as `URI`, httpRequest.httpMethod as `Method`\n| filter action == \"BLOCK\"\n| limit 100",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Bots",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"ALL_BOTS\" Region=\"eu-west-2\" WebACL=\"cdp-sirsi-acl\" VerificationStatus=\"bot:verified\" :aws.AccountId=LOCAL', 'Sum', 60))",
     "label": "Verified",
     "metricEditorMode": 1,
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "COUNT", "type": "function" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "CountedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SUM(SEARCH('{AWS/WAFV2,LabelName,LabelNamespace,WebACL,Region} LabelName=\"HostingProviderIPList\" Region=\"eu-west-2\" LabelNamespace=\"awswaf:managed:aws:anonymous-ip-list\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" NOT \"ALL\"', 'Sum', 60))",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"ALL_BOTS\" Region=\"eu-west-2\" WebACL=\"cdp-sirsi-acl\" VerificationStatus=\"bot:unverified\" :aws.AccountId=LOCAL', 'Sum', 60))",
     "label": "Unverified",
     "metricEditorMode": 1,
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "COUNT", "type": "function" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "CountedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SUM(SEARCH('{AWS/WAFV2,LabelName,LabelNamespace,WebACL,Region} LabelName=\"HostingProviderIPList\" Region=\"eu-west-2\" LabelNamespace=\"awswaf:managed:aws:anonymous-ip-list\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" NOT \"ALL\"', 'Sum', 60))",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('AWS/WAFV2 MetricName=(\"SampleBlockedRequest\" OR \"SampleAllowedRequest\" OR \"SampleCaptchaRequest\" OR \"SampleChallengeRequest\") BotCategory=\"NON_BOT\" Region=\"eu-west-2\" WebACL=\"cdp-sirsi-acl\" :aws.AccountId=LOCAL', 'Sum', 60))",
     "label": "Non-bot",
     "metricEditorMode": 1,
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "COUNT", "type": "function" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "CountedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SUM(SEARCH('{AWS/WAFV2,LabelName,LabelNamespace,WebACL,Region} LabelName=\"HostingProviderIPList\" Region=\"eu-west-2\" LabelNamespace=\"awswaf:managed:aws:anonymous-ip-list\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" NOT \"ALL\"', 'Sum', 60))",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Last 100 Observed",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 27 },
   "targets": [
    {
     "expression": "fields @timestamp, action as `Action`, httpRequest.clientIp as `Client IP`, httpRequest.country as `Country`, httpRequest.uri as `URI`, httpRequest.httpMethod as `Method`\n| filter action != \"BLOCK\"\n| limit 100",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:aws-waf-logs-cdp-sirsi:*",
       "name": "aws-waf-logs-cdp-sirsi"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "piechart",
   "description": "Last 60 minutes",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "SUM(SEARCH('{AWS/WAFV2,Device,WebACL,Region} Region=\"eu-west-2\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" Device=\"Desktop\"', 'Sum', 60))",
     "label": "Desktop",
     "metricEditorMode": 1,
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "COUNT", "type": "function" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "CountedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SUM(SEARCH('{AWS/WAFV2,LabelName,LabelNamespace,WebACL,Region} LabelName=\"HostingProviderIPList\" Region=\"eu-west-2\" LabelNamespace=\"awswaf:managed:aws:anonymous-ip-list\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" NOT \"ALL\"', 'Sum', 60))",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('{AWS/WAFV2,Device,WebACL,Region} Region=\"eu-west-2\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" Device=\"Tablet\"', 'Sum', 60))",
     "label": "Tablet",
     "metricEditorMode": 1,
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "COUNT", "type": "function" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "CountedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SUM(SEARCH('{AWS/WAFV2,LabelName,LabelNamespace,WebACL,Region} LabelName=\"HostingProviderIPList\" Region=\"eu-west-2\" LabelNamespace=\"awswaf:managed:aws:anonymous-ip-list\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" NOT \"ALL\"', 'Sum', 60))",
     "statistic": "Average"
    },
    {
     "expression": "SUM(SEARCH('{AWS/WAFV2,Device,WebACL,Region} Region=\"eu-west-2\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" Device=\"Mobile\"', 'Sum', 60))",
     "label": "Mobile",
     "metricEditorMode": 1,
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Rule", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "COUNT", "type": "function" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "CountedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SUM(SEARCH('{AWS/WAFV2,LabelName,LabelNamespace,WebACL,Region} LabelName=\"HostingProviderIPList\" Region=\"eu-west-2\" LabelNamespace=\"awswaf:managed:aws:anonymous-ip-list\" MetricName=(\"BlockedRequests\" OR \"AllowedRequests\" OR \"CaptchaRequests\" OR \"ChallengeRequests\") WebACL=\"cdp-sirsi-acl\" :aws.AccountId = \"LOCAL\" NOT \"ALL\"', 'Sum', 60))",
     "statistic": "Average"
    }
   ]
  }
 ]
}