[SERVICE]
    Parsers_File parsers/*.conf

@INCLUDE inputs/*.conf

[INPUT]
    Name tcp
    Listen 0.0.0.0
    Port 2020
    Format none
    Tag health.ping

[OUTPUT]
    Name prometheus_exporter
    Match *
    Host 0.0.0.0
    Port 2021

[OUTPUT]
    Name cloudwatch
    Match default.*
    region eu-west-2
    log_group_name /ecs/fluentbit
    log_stream_prefix FTS
    auto_create_group true
