version: 0.2

phases:
  pre_build:
    commands:
      - terraform version
      - terragrunt --version
      - jq --version
      - aws sts assume-role --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/cdp-sirsi-${TG_ENVIRONMENT}-terraform --role-session-name CodeBuildSession > /tmp/assumed_role.json
      - export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' /tmp/assumed_role.json)
      - export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' /tmp/assumed_role.json)
      - export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' /tmp/assumed_role.json)

  build:
    commands:
      - cd /terragrunt/components/service/ecs
      - terragrunt apply --auto-approve
      - cd /terragrunt/components/service/api-gateway
      - terragrunt apply --auto-approve
