namespace CO.CDP.OrganisationApp.Constants;

public static class ErrorCodes
{
    public const string ORGANISATION_ALREADY_EXISTS = "ORGANISATION_ALREADY_EXISTS";
    public const string INVALID_OPERATION = "INVALID_OPERATION";
    public const string ARGUMENT_NULL = "ARGUMENT_NULL";
    public const string PERSON_ALREADY_EXISTS = "PERSON_ALREADY_EXISTS";

    public const string PERSON_DOES_NOT_EXIST = "PERSON_DOES_NOT_EXIST";

    public const string UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY";

    public const string GENERIC_ERROR = "GENERIC_ERROR";


    public const string UNKNOWN_ORGANISATION = "UNKNOWN_ORGANISATION";
    public const string BUYER_INFO_NOT_EXISTS = "BUYER_INFO_NOT_EXISTS";
    public const string UNKNOWN_BUYER_INFORMATION_UPDATE_TYPE = "UNKNOWN_BUYER_INFORMATION_UPDATE_TYPE";
    public const string PERSON_INVITE_ALREADY_CLAIMED = "PERSON_INVITE_ALREADY_CLAIMED";
    public const string APIKEY_NAME_ALREADY_EXISTS = "APIKEY_NAME_ALREADY_EXISTS";
    public const string EMAIL_ALREADY_EXISTS_WITHIN_ORGANISATION = "EMAIL_ALREADY_EXISTS_WITHIN_ORGANISATION";

    public const string ORGANISATION_UPDATE_INVALID_INPUT = "ORGANISATION_UPDATE_INVALID_INPUT";
    public const string INVITE_EMAIL_ALREADY_EXISTS_FOR_ORGANISATION = "INVITE_EMAIL_ALREADY_EXISTS_FOR_ORGANISATION";
    public const string PERSON_ALREADY_ADDED_TO_ORGANISATION = "PERSON_ALREADY_ADDED_TO_ORGANISATION";

    public const string ORGANISATION_MISSING_NAME = "ORGANISATION_MISSING_NAME";
    public const string ORGANISATION_MISSING_ROLES = "ORGANISATION_MISSING_ROLES";
    public const string ORGANISATION_MISSING_CONTACTPOINT = "ORGANISATION_MISSING_CONTACTPOINT";
    public const string ORGANISATION_NOPRIMARY_IDENTIFIER = "ORGANISATION_NOPRIMARY_IDENTIFIER";
    public const string ORGANISATION_MISSING_EMAIL = "ORGANISATION_MISSING_EMAIL";
    public const string ORGANISATION_EMAIL_DOES_NOT_EXISTS = "ORGANISATION_EMAIL_DOES_NOT_EXISTS";
    public const string ORGANISATION_MISSING_ADDRESS = "ORGANISATION_MISSING_ADDRESS";
    public const string ORGANISATION_MISSING_REGISTERED_ADDRESS = "ORGANISATION_MISSING_REGISTERED_ADDRESS";
    public const string ORGANISATION_MISSING_ADDITIONAL_IDENTIFIERS = "ORGANISATION_MISSING_ADDITIONAL_IDENTIFIERS";
    public const string ORGANISATION_MISSING_IDENTIFIER_NUMBER = "ORGANISATION_MISSING_IDENTIFIER_NUMBER";
    public const string ORGANISATION_IDENTIFIER_NUMBER_ALREADY_EXISTS = "ORGANISATION_IDENTIFIER_NUMBER_ALREADY_EXISTS";      
}