namespace CO.CDP.OrganisationApp.Constants;

public static class ErrorCodes
{
    public const string ORGANISATION_ALREADY_EXISTS = "ORGANISATION_ALREADY_EXISTS";
    public const string INVALID_OPERATION = "INVALID_OPERATION";
    public const string ARGUMENT_NULL = "ARGUMENT_NULL";
    public const string PERSON_ALREADY_EXISTS = "PERSON_ALREADY_EXISTS";

    public const string PERSON_DOES_NOT_EXIST = "PERSON_DOES_NOT_EXIST";

    public const string UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY";

    public const string GENERIC_ERROR = "GENERIC_ERROR";


    public const string UNKNOWN_ORGANISATION = "UNKNOWN_ORGANISATION";
    public const string BUYER_INFO_NOT_EXISTS = "BUYER_INFO_NOT_EXISTS";
    public const string UNKNOWN_BUYER_INFORMATION_UPDATE_TYPE = "UNKNOWN_BUYER_INFORMATION_UPDATE_TYPE";
    public const string PERSON_INVITE_ALREADY_CLAIMED = "PERSON_INVITE_ALREADY_CLAIMED";
    public const string APIKEY_NAME_ALREADY_EXISTS = "APIKEY_NAME_ALREADY_EXISTS";
    public const string EMAIL_ALREADY_EXISTS_WITHIN_ORGANISATION = "EMAIL_ALREADY_EXISTS_WITHIN_ORGANISATION";
    public const string INVITE_EMAIL_ALREADY_EXISTS_FOR_ORGANISATION = "INVITE_EMAIL_ALREADY_EXISTS_FOR_ORGANISATION";
    public const string PERSON_ALREADY_ADDED_TO_ORGANISATION = "PERSON_ALREADY_ADDED_TO_ORGANISATION";
}