@healthCheck_HostAddress = http://localhost:3030

### Get Health Status
GET {{healthCheck_HostAddress}}/health
Accept: application/json

### Test SQS Connectivity
GET {{healthCheck_HostAddress}}/sqs/test
Accept: application/json

### Test SQS Connectivity
GET {{healthCheck_HostAddress}}/swagger/v1/swagger.json
Accept: application/json
