{
 "title": "System Performance",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ecs_log_groups",
    "label": "ecs_log_groups",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Services 4XX counts (404 excluded)",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields concat( @log, \" [ \", StatusCode, \" ]\") as Status\n| filter ispresent(StatusCode)\n| filter StatusCode >= 400 and StatusCode < 500\n| filter StatusCode != 404\n\n",
     "logGroups": [
      { "arn": "$ecs_log_groups", "name": "$ecs_log_groups" },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/authority:*",
       "name": "/ecs/authority"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/av-scanner-app:*",
       "name": "/ecs/av-scanner-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/clamav-rest:*",
       "name": "/ecs/clamav-rest"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/commercial-tools-api:*",
       "name": "/ecs/commercial-tools-api"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/commercial-tools-app:*",
       "name": "/ecs/commercial-tools-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-api:*",
       "name": "/ecs/user-management-api"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-app:*",
       "name": "/ecs/user-management-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/data-sharing:*",
       "name": "/ecs/data-sharing"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification:*",
       "name": "/ecs/entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification-migrations:*",
       "name": "/ecs/entity-verification-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/forms:*",
       "name": "/ecs/forms"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation:*",
       "name": "/ecs/organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-app:*",
       "name": "/ecs/organisation-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-information-migrations:*",
       "name": "/ecs/organisation-information-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-entity-verification:*",
       "name": "/ecs/outbox-processor-entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation:*",
       "name": "/ecs/outbox-processor-organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation-user-management:*",
       "name": "/ecs/outbox-processor-organisation-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-person-user-management:*",
       "name": "/ecs/outbox-processor-person-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/person:*",
       "name": "/ecs/person"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/tenant:*",
       "name": "/ecs/tenant"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/scheduled-worker:*",
       "name": "/ecs/scheduled-worker"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Service Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, concat( @log, \" [ \", Version, \" ]\") as ServiceVersion\n| filter ispresent(Version)\n| filter toMillis(@timestamp) >= toMillis(datefloor(@timestamp, 5m))",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/authority:*",
       "name": "/ecs/authority"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/av-scanner-app:*",
       "name": "/ecs/av-scanner-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/commercial-tools-api:*",
       "name": "/ecs/commercial-tools-api"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/commercial-tools-app:*",
       "name": "/ecs/commercial-tools-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-api:*",
       "name": "/ecs/user-management-api"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-app:*",
       "name": "/ecs/user-management-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/data-sharing:*",
       "name": "/ecs/data-sharing"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification:*",
       "name": "/ecs/entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification-migrations:*",
       "name": "/ecs/entity-verification-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/forms:*",
       "name": "/ecs/forms"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/fts-app:*",
       "name": "/ecs/fts-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/fts-search-api:*",
       "name": "/ecs/fts-search-api"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/fts-search-indexer:*",
       "name": "/ecs/fts-search-indexer"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation:*",
       "name": "/ecs/organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-app:*",
       "name": "/ecs/organisation-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-information-migrations:*",
       "name": "/ecs/organisation-information-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation:*",
       "name": "/ecs/outbox-processor-organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation-user-management:*",
       "name": "/ecs/outbox-processor-organisation-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-person-user-management:*",
       "name": "/ecs/outbox-processor-person-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-entity-verification:*",
       "name": "/ecs/outbox-processor-entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/person:*",
       "name": "/ecs/person"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/tenant:*",
       "name": "/ecs/tenant"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Services 5XX counts",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expression": "fields concat( @log, \" [ \", StatusCode, \" ]\") as Status\n| filter ispresent(StatusCode)\n| filter StatusCode >= 500\n\n",
     "logGroups": [
      { "arn": "$ecs_log_groups", "name": "$ecs_log_groups" },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/authority:*",
       "name": "/ecs/authority"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/av-scanner-app:*",
       "name": "/ecs/av-scanner-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/clamav-rest:*",
       "name": "/ecs/clamav-rest"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/commercial-tools-api:*",
       "name": "/ecs/commercial-tools-api"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/commercial-tools-app:*",
       "name": "/ecs/commercial-tools-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-api:*",
       "name": "/ecs/user-management-api"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-app:*",
       "name": "/ecs/user-management-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/data-sharing:*",
       "name": "/ecs/data-sharing"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification:*",
       "name": "/ecs/entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification-migrations:*",
       "name": "/ecs/entity-verification-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/forms:*",
       "name": "/ecs/forms"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation:*",
       "name": "/ecs/organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-app:*",
       "name": "/ecs/organisation-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-information-migrations:*",
       "name": "/ecs/organisation-information-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-entity-verification:*",
       "name": "/ecs/outbox-processor-entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation:*",
       "name": "/ecs/outbox-processor-organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation-user-management:*",
       "name": "/ecs/outbox-processor-organisation-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-person-user-management:*",
       "name": "/ecs/outbox-processor-person-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/person:*",
       "name": "/ecs/person"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/tenant:*",
       "name": "/ecs/tenant"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/scheduled-worker:*",
       "name": "/ecs/scheduled-worker"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HTTP Request Code Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Request Count",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "ELB 5XX",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "ELB 4XX",
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "ELB 3XX",
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP Redirect Code Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Redirect Counts",
     "metricName": "HTTP_Redirect_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1m",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 2XX",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 5XX",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 4XX",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 3XX",
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "cdp-sirsi", "ServiceName": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "period": "5m",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "cdp-sirsi", "ServiceName": "*" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "All Services Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expression": "fields @timestamp, @message, StatusCode\n| filter ispresent(StatusCode)\n| stats count() as Hits by bin(1m), StatusCode\n",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/authority:*",
       "name": "/ecs/authority"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/av-scanner-app:*",
       "name": "/ecs/av-scanner-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/data-sharing:*",
       "name": "/ecs/data-sharing"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/clamav-rest:*",
       "name": "/ecs/clamav-rest"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification:*",
       "name": "/ecs/entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification-migrations:*",
       "name": "/ecs/entity-verification-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/forms:*",
       "name": "/ecs/forms"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation:*",
       "name": "/ecs/organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-app:*",
       "name": "/ecs/organisation-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-information-migrations:*",
       "name": "/ecs/organisation-information-migrations"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-entity-verification:*",
       "name": "/ecs/outbox-processor-entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation:*",
       "name": "/ecs/outbox-processor-organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation-user-management:*",
       "name": "/ecs/outbox-processor-organisation-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-person-user-management:*",
       "name": "/ecs/outbox-processor-person-user-management"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/person:*",
       "name": "/ecs/person"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/tenant:*",
       "name": "/ecs/tenant"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(1m)",
      "StatusCode"
     ]
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cluster" },
     "label": "SIRSI",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cluster-0" },
     "label": "SIRSI 0",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cluster-1" },
     "label": "SIRSI 1",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-ev-cluster" },
     "label": "EV",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-ev-cluster-0" },
     "label": "EV 0",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-ev-cluster-1" },
     "label": "EV 1",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-fts-cluster" },
     "label": "FTS",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-fts-cluster-0" },
     "label": "FTS 0",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-fts-cluster-1" },
     "label": "FTS 1",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cfs-cluster" },
     "label": "CFS",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cfs-cluster-0" },
     "label": "CFS 0",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cfs-cluster-1" },
     "label": "CFS 1",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cluster" },
     "label": "SIRSI",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-ev-cluster" },
     "label": "EV",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-fts-cluster" },
     "label": "FTS",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cfs-cluster" },
     "label": "CFS",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cluster" },
     "label": "SIRSI",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-ev-cluster" },
     "label": "EV",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-fts-cluster" },
     "label": "FTS",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cfs-cluster" },
     "label": "CFS",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "DB Load",
   "type": "timeseries",
   "description": "The number of active sessions for the database",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cluster-0" },
     "label": "SIRSI 0",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cluster-1" },
     "label": "SIRSI 1",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-ev-cluster-0" },
     "label": "EV 0",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-ev-cluster-1" },
     "label": "EV 1",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-fts-cluster-0" },
     "label": "FTS 0",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-fts-cluster-1" },
     "label": "FTS 1",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cfs-cluster-0" },
     "label": "CFS 0",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cfs-cluster-1" },
     "label": "CFS 1",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "*" },
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Capacity Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "*" },
     "metricName": "DatabaseCapacityUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Engine CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "*" },
     "metricName": "EngineCPUUtilization",
     "namespace": "AWS/ElastiCache",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/ElastiCache",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Database Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "*" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "period": "5m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "SQS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Approximate Number Of Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-av-scanner.fifo"
     },
     "label": "AV Scanner",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-entity-verification.fifo"
     },
     "label": "Entity Verification",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-organisation.fifo"
     },
     "label": "Organisation",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Approximate Number Of Messages Delayed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-av-scanner.fifo"
     },
     "label": "AV Scanner",
     "metricName": "ApproximateNumberOfMessagesDelayed",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-entity-verification.fifo"
     },
     "label": "Entity Verification",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-organisation.fifo"
     },
     "label": "Organisation",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Approximate Number Of Messages in DLQ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-av-scanner-deadletter.fifo"
     },
     "label": "AV Scanner",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-entity-verification-deadletter.fifo"
     },
     "label": "Entity Verification",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "QueueName": "CDP_SIRSI_ENVIRONMENT-organisation-deadletter.fifo"
     },
     "label": "Organisation",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "1m",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}