{
 "title": "System Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Request Code Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Request Count",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "ELB 5XX",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "ELB 4XX",
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "ELB 3XX",
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "HTTP Redirect Code Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Redirect Counts",
     "metricName": "HTTP_Redirect_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 2XX",
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 5XX",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 4XX",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "*" },
     "label": "Target 3XX",
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "app/cdp-sirsi/9e67fe66e4a0652c" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "cdp-sirsi", "ServiceName": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "cdp-sirsi", "ServiceName": "*" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "All Services Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, StatusCode\n| filter ispresent(StatusCode)\n| stats count() as Hits by bin(1m), StatusCode\n",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/forms:*",
       "name": "/ecs/forms"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/entity-verification:*",
       "name": "/ecs/entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/data-sharing:*",
       "name": "/ecs/data-sharing"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/clamav-rest:*",
       "name": "/ecs/clamav-rest"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/av-scanner-app:*",
       "name": "/ecs/av-scanner-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/authority:*",
       "name": "/ecs/authority"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation:*",
       "name": "/ecs/organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/organisation-app:*",
       "name": "/ecs/organisation-app"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-entity-verification:*",
       "name": "/ecs/outbox-processor-entity-verification"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/outbox-processor-organisation:*",
       "name": "/ecs/outbox-processor-organisation"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/person:*",
       "name": "/ecs/person"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/tenant:*",
       "name": "/ecs/tenant"
      },
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/etc/entity-verification:*",
       "name": "/etc/entity-verification"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(1m)",
      "StatusCode"
     ]
    }
   ]
  },
  {
   "title": "All Services Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expression": "fields @timestamp, StatusCode\n| filter ispresent(StatusCode)\n| filter StatusCode >= 400\n| stats count() as Hits by bin(1m), StatusCode\n",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/forms:*",
       "name": "/ecs/forms"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [
      "bin(1m)",
      "StatusCode"
     ]
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cluster" },
     "label": "SIRSI",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-ev-cluster" },
     "label": "EV",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-cluster" },
     "label": "SIRSI",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBClusterIdentifier": "cdp-sirsi-ev-cluster" },
     "label": "EV",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "DB Load",
   "type": "timeseries",
   "description": "The number of active sessions for the database",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cluster-0" },
     "label": "SIRSI 0",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-cluster-1" },
     "label": "SIRSI 1",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-ev-cluster-0" },
     "label": "EV 0",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "cdp-sirsi-ev-cluster-1" },
     "label": "EV 1",
     "metricName": "DBLoad",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}