{
 "title": "User Management API",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Last 5 Errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, @@m as Message, @@l as level, Version, RequestPath, RequestId, ConnectionId, EventId, @@tr as TR, @@sp as SP, @@t as T, @message  \n| filter level = \"Error\" \n| sort @timestamp desc \n| limit 5",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-api:*",
       "name": "/ecs/user-management-api"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Last 10 Warning",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expression": "fields @timestamp, @@m as Message, @@l as level, Version, RequestPath, RequestId, ConnectionId, EventId, @@tr as TR, @@sp as SP, @@t as T, @message  \n| filter level = \"Warning\" \n| sort @timestamp desc \n| limit 5",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-api:*",
       "name": "/ecs/user-management-api"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "All",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "fields @timestamp, @@m as Message, @@l as level, Version, RequestPath, RequestId, ConnectionId, EventId, @@tr as TR, @@sp as SP, @@t as T, @message  \n| sort @timestamp desc",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/user-management-api:*",
       "name": "/ecs/user-management-api"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}