// <auto-generated />
using System;
using CO.CDP.OrganisationInformation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CO.CDP.OrganisationInformation.Persistence.Migrations
{
    [DbContext(typeof(OrganisationInformationContext))]
    [Migration("20240807073912_MoveOrganisationToSharedConsent")]
    partial class MoveOrganisationToSharedConsent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "connected_entity_type", new[] { "organisation", "individual", "trust_or_trustee" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "connected_organisation_category", new[] { "registered_company", "director_or_the_same_responsibilities", "parent_or_subsidiary_company", "a_company_your_organisation_has_taken_over", "any_other_organisation_with_significant_influence_or_control" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "connected_person_category", new[] { "person_with_significant_control", "director_or_individual_with_the_same_responsibilities", "any_other_individual_with_significant_influence_or_control" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "connected_person_type", new[] { "individual", "trust_or_trustee" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "control_condition", new[] { "none", "owns_shares", "has_voting_rights", "can_appoint_or_remove_directors", "has_other_significant_influence_or_control" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_name");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.AuthenticationKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("integer")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_authentication_keys");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_authentication_keys_key");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_authentication_keys_organisation_id");

                    b.ToTable("authentication_keys", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.ConnectedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyHouseNumber")
                        .HasColumnType("text")
                        .HasColumnName("company_house_number");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("HasCompnayHouseNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("has_compnay_house_number");

                    b.Property<string>("OverseasCompanyNumber")
                        .HasColumnType("text")
                        .HasColumnName("overseas_company_number");

                    b.Property<string>("RegisterName")
                        .HasColumnType("text")
                        .HasColumnName("register_name");

                    b.Property<DateTimeOffset?>("RegisteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_date");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("SupplierOrganisationId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_organisation_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_connected_entities");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_connected_entities_guid");

                    b.HasIndex("SupplierOrganisationId")
                        .HasDatabaseName("ix_connected_entities_supplier_organisation_id");

                    b.ToTable("connected_entities", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_forms");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("address_value");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("bool_value");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_value");

                    b.Property<DateTime?>("EndValue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_value");

                    b.Property<int>("FormAnswerSetId")
                        .HasColumnType("integer")
                        .HasColumnName("form_answer_set_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("double precision")
                        .HasColumnName("numeric_value");

                    b.Property<string>("OptionValue")
                        .HasColumnType("text")
                        .HasColumnName("option_value");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("StartValue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_value");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_form_answers");

                    b.HasIndex("FormAnswerSetId")
                        .HasDatabaseName("ix_form_answers_form_answer_set_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_form_answers_question_id");

                    b.ToTable("form_answers", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormAnswerSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<int>("SharedConsentId")
                        .HasColumnType("integer")
                        .HasColumnName("shared_consent_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_form_answer_sets");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_form_answer_sets_section_id");

                    b.HasIndex("SharedConsentId")
                        .HasDatabaseName("ix_form_answer_sets_shared_consent_id");

                    b.ToTable("form_answer_sets", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int?>("NextQuestionAlternativeId")
                        .HasColumnType("integer")
                        .HasColumnName("next_question_alternative_id");

                    b.Property<int?>("NextQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("next_question_id");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<string>("SummaryTitle")
                        .HasColumnType("text")
                        .HasColumnName("summary_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_form_questions");

                    b.HasIndex("NextQuestionAlternativeId")
                        .HasDatabaseName("ix_form_questions_next_question_alternative_id");

                    b.HasIndex("NextQuestionId")
                        .HasDatabaseName("ix_form_questions_next_question_id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_form_questions_section_id");

                    b.ToTable("form_questions", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsMultipleAnswerSets")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_multiple_answer_sets");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_form_sections");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_sections_form_id");

                    b.ToTable("form_sections", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.SharedConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_reference");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.Property<string>("FormVersionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("form_version_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer")
                        .HasColumnName("organisation_id");

                    b.Property<int>("SubmissionState")
                        .HasColumnType("integer")
                        .HasColumnName("submission_state");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_shared_consents");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_shared_consents_form_id");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_shared_consents_organisation_id");

                    b.ToTable("shared_consents", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_guid");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_organisations_tenant_id");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.OrganisationPerson", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer")
                        .HasColumnName("organisation_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OrganisationId", "PersonId")
                        .HasName("pk_organisation_person");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_organisation_person_person_id");

                    b.ToTable("organisation_person", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserUrn")
                        .HasColumnType("text")
                        .HasColumnName("user_urn");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_email");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_guid");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_guid");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_name");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.TenantPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("PersonId", "TenantId")
                        .HasName("pk_tenant_person");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_person_tenant_id");

                    b.ToTable("tenant_person", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.AuthenticationKey", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .HasConstraintName("fk_authentication_keys_organisations_organisation_id");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.ConnectedEntity", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Organisation", "SupplierOrganisation")
                        .WithMany()
                        .HasForeignKey("SupplierOrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connected_entities_organisations_supplier_organisation_id");

                    b.OwnsMany("CO.CDP.OrganisationInformation.Persistence.ConnectedEntity+ConnectedEntityAddress", "Addresses", b1 =>
                        {
                            b1.Property<int>("ConnectedEntityId")
                                .HasColumnType("integer")
                                .HasColumnName("connected_entity_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AddressId")
                                .HasColumnType("integer")
                                .HasColumnName("address_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("ConnectedEntityId", "Id")
                                .HasName("pk_connected_entity_address");

                            b1.HasIndex("AddressId")
                                .HasDatabaseName("ix_connected_entity_address_address_id");

                            b1.ToTable("connected_entity_address", (string)null);

                            b1.HasOne("CO.CDP.OrganisationInformation.Persistence.Address", "Address")
                                .WithMany()
                                .HasForeignKey("AddressId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_connected_entity_address_address_address_id");

                            b1.WithOwner()
                                .HasForeignKey("ConnectedEntityId")
                                .HasConstraintName("fk_connected_entity_address_connected_entities_connected_entit");

                            b1.Navigation("Address");
                        });

                    b.OwnsOne("CO.CDP.OrganisationInformation.Persistence.ConnectedEntity+ConnectedIndividualTrust", "IndividualOrTrust", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("connected_individual_trust_id");

                            b1.Property<int>("Category")
                                .HasColumnType("integer")
                                .HasColumnName("category");

                            b1.Property<int>("ConnectedType")
                                .HasColumnType("integer")
                                .HasColumnName("connected_type");

                            b1.Property<int[]>("ControlCondition")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("control_condition");

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<DateTimeOffset?>("DateOfBirth")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date_of_birth");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<string>("Nationality")
                                .HasColumnType("text")
                                .HasColumnName("nationality");

                            b1.Property<Guid?>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("person_id");

                            b1.Property<string>("ResidentCountry")
                                .HasColumnType("text")
                                .HasColumnName("resident_country");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("Id")
                                .HasName("pk_connected_individual_trust");

                            b1.ToTable("connected_individual_trust", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_connected_individual_trust_connected_entities_connected_ind");
                        });

                    b.OwnsOne("CO.CDP.OrganisationInformation.Persistence.ConnectedEntity+ConnectedOrganisation", "Organisation", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasColumnName("connected_organisation_id");

                            b1.Property<int>("Category")
                                .HasColumnType("integer")
                                .HasColumnName("category");

                            b1.Property<int[]>("ControlCondition")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("control_condition");

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<DateTimeOffset?>("InsolvencyDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("insolvency_date");

                            b1.Property<string>("LawRegistered")
                                .HasColumnType("text")
                                .HasColumnName("law_registered");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<Guid?>("OrganisationId")
                                .HasColumnType("uuid")
                                .HasColumnName("organisation_id");

                            b1.Property<string>("RegisteredLegalForm")
                                .HasColumnType("text")
                                .HasColumnName("registered_legal_form");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("Id")
                                .HasName("pk_connected_organisation");

                            b1.ToTable("connected_organisation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_connected_organisation_connected_entities_connected_organis");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("IndividualOrTrust");

                    b.Navigation("Organisation");

                    b.Navigation("SupplierOrganisation");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormAnswer", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.FormAnswerSet", "FormAnswerSet")
                        .WithMany("Answers")
                        .HasForeignKey("FormAnswerSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_answers_form_answer_sets_form_answer_set_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.FormQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_answers_form_questions_question_id");

                    b.Navigation("FormAnswerSet");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormAnswerSet", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.FormSection", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_answer_sets_form_section_section_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.SharedConsent", "SharedConsent")
                        .WithMany("AnswerSets")
                        .HasForeignKey("SharedConsentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_answer_sets_shared_consents_shared_consent_id");

                    b.Navigation("Section");

                    b.Navigation("SharedConsent");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormQuestion", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.FormQuestion", "NextQuestionAlternative")
                        .WithMany()
                        .HasForeignKey("NextQuestionAlternativeId")
                        .HasConstraintName("fk_form_questions_form_questions_next_question_alternative_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.FormQuestion", "NextQuestion")
                        .WithMany()
                        .HasForeignKey("NextQuestionId")
                        .HasConstraintName("fk_form_questions_form_questions_next_question_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.FormSection", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_questions_form_sections_section_id");

                    b.Navigation("NextQuestion");

                    b.Navigation("NextQuestionAlternative");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormSection", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.Form", "Form")
                        .WithMany("Sections")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_sections_forms_form_id");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.SharedConsent", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Forms.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shared_consents_forms_form_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shared_consents_organisations_organisation_id");

                    b.Navigation("Form");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Organisation", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Tenant", "Tenant")
                        .WithMany("Organisations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisations_tenants_tenant_id");

                    b.OwnsOne("CO.CDP.OrganisationInformation.Persistence.Organisation+BuyerInformation", "BuyerInfo", b1 =>
                        {
                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("BuyerType")
                                .HasColumnType("text")
                                .HasColumnName("buyer_type");

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<int[]>("DevolvedRegulations")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("devolved_regulations");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("OrganisationId")
                                .HasName("pk_buyer_information");

                            b1.ToTable("buyer_information", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_buyer_information_organisations_id");
                        });

                    b.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+ContactPoint", "ContactPoints", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("organisation_id");

                            b1.Property<string>("Telephone")
                                .HasColumnType("text")
                                .HasColumnName("telephone");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Url")
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("Id")
                                .HasName("pk_contact_points");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_contact_points_organisation_id");

                            b1.ToTable("contact_points", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_contact_points_organisations_organisation_id");
                        });

                    b.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+Identifier", "Identifiers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("IdentifierId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("identifier_id");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("legal_name");

                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("organisation_id");

                            b1.Property<bool>("Primary")
                                .HasColumnType("boolean")
                                .HasColumnName("primary");

                            b1.Property<string>("Scheme")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scheme");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Uri")
                                .HasColumnType("text")
                                .HasColumnName("uri");

                            b1.HasKey("Id")
                                .HasName("pk_identifiers");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_identifiers_organisation_id");

                            b1.ToTable("identifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_identifiers_organisations_organisation_id");
                        });

                    b.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+OrganisationAddress", "Addresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AddressId")
                                .HasColumnType("integer")
                                .HasColumnName("address_id");

                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("organisation_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_organisation_address");

                            b1.HasIndex("AddressId")
                                .HasDatabaseName("ix_organisation_address_address_id");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_organisation_address_organisation_id");

                            b1.ToTable("organisation_address", (string)null);

                            b1.HasOne("CO.CDP.OrganisationInformation.Persistence.Address", "Address")
                                .WithMany()
                                .HasForeignKey("AddressId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_organisation_address_address_address_id");

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_organisation_address_organisations_organisation_id");

                            b1.Navigation("Address");
                        });

                    b.OwnsOne("CO.CDP.OrganisationInformation.Persistence.Organisation+SupplierInformation", "SupplierInfo", b1 =>
                        {
                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<bool>("CompletedConnectedPerson")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_connected_person");

                            b1.Property<bool>("CompletedEmailAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_email_address");

                            b1.Property<bool>("CompletedLegalForm")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_legal_form");

                            b1.Property<bool>("CompletedOperationType")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_operation_type");

                            b1.Property<bool>("CompletedPostalAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_postal_address");

                            b1.Property<bool>("CompletedQualification")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_qualification");

                            b1.Property<bool>("CompletedRegAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_reg_address");

                            b1.Property<bool>("CompletedTradeAssurance")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_trade_assurance");

                            b1.Property<bool>("CompletedVat")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_vat");

                            b1.Property<bool>("CompletedWebsiteAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_website_address");

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<int[]>("OperationTypes")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("operation_types");

                            b1.Property<int?>("SupplierType")
                                .HasColumnType("integer")
                                .HasColumnName("supplier_type");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("OrganisationId")
                                .HasName("pk_supplier_information");

                            b1.ToTable("supplier_information", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_supplier_information_organisations_id");

                            b1.OwnsOne("CO.CDP.OrganisationInformation.Persistence.Organisation+LegalForm", "LegalForm", b2 =>
                                {
                                    b2.Property<int>("SupplierInformationOrganisationId")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("CreatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.Property<string>("LawRegistered")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("law_registered");

                                    b2.Property<string>("RegisteredLegalForm")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("registered_legal_form");

                                    b2.Property<bool>("RegisteredUnderAct2006")
                                        .HasColumnType("boolean")
                                        .HasColumnName("registered_under_act2006");

                                    b2.Property<DateTimeOffset>("RegistrationDate")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("registration_date");

                                    b2.Property<DateTimeOffset>("UpdatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.HasKey("SupplierInformationOrganisationId")
                                        .HasName("pk_legal_forms");

                                    b2.ToTable("legal_forms", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierInformationOrganisationId")
                                        .HasConstraintName("fk_legal_forms_supplier_information_id");
                                });

                            b1.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+Qualification", "Qualifications", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("AwardedByPersonOrBodyName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("awarded_by_person_or_body_name");

                                    b2.Property<DateTimeOffset>("CreatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.Property<DateTimeOffset>("DateAwarded")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("date_awarded");

                                    b2.Property<Guid>("Guid")
                                        .HasColumnType("uuid")
                                        .HasColumnName("guid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.Property<int>("SupplierInformationOrganisationId")
                                        .HasColumnType("integer")
                                        .HasColumnName("supplier_information_organisation_id");

                                    b2.Property<DateTimeOffset>("UpdatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.HasKey("Id")
                                        .HasName("pk_qualifications");

                                    b2.HasIndex("Guid")
                                        .IsUnique()
                                        .HasDatabaseName("ix_qualifications_guid");

                                    b2.HasIndex("SupplierInformationOrganisationId")
                                        .HasDatabaseName("ix_qualifications_supplier_information_organisation_id");

                                    b2.ToTable("qualifications", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierInformationOrganisationId")
                                        .HasConstraintName("fk_qualifications_supplier_information_supplier_information_or");
                                });

                            b1.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+TradeAssurance", "TradeAssurances", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("AwardedByPersonOrBodyName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("awarded_by_person_or_body_name");

                                    b2.Property<DateTimeOffset>("CreatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.Property<DateTimeOffset>("DateAwarded")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("date_awarded");

                                    b2.Property<Guid>("Guid")
                                        .HasColumnType("uuid")
                                        .HasColumnName("guid");

                                    b2.Property<string>("ReferenceNumber")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("reference_number");

                                    b2.Property<int>("SupplierInformationOrganisationId")
                                        .HasColumnType("integer")
                                        .HasColumnName("supplier_information_organisation_id");

                                    b2.Property<DateTimeOffset>("UpdatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.HasKey("Id")
                                        .HasName("pk_trade_assurances");

                                    b2.HasIndex("Guid")
                                        .IsUnique()
                                        .HasDatabaseName("ix_trade_assurances_guid");

                                    b2.HasIndex("SupplierInformationOrganisationId")
                                        .HasDatabaseName("ix_trade_assurances_supplier_information_organisation_id");

                                    b2.ToTable("trade_assurances", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierInformationOrganisationId")
                                        .HasConstraintName("fk_trade_assurances_supplier_information_supplier_information_");
                                });

                            b1.Navigation("LegalForm");

                            b1.Navigation("Qualifications");

                            b1.Navigation("TradeAssurances");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("BuyerInfo");

                    b.Navigation("ContactPoints");

                    b.Navigation("Identifiers");

                    b.Navigation("SupplierInfo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.OrganisationPerson", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Organisation", "Organisation")
                        .WithMany("OrganisationPersons")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_person_organisations_organisation_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Person", "Person")
                        .WithMany("PersonOrganisations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_person_persons_person_id");

                    b.Navigation("Organisation");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.TenantPerson", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_person_persons_person_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_person_tenants_tenant_id");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.Form", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormAnswerSet", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.FormSection", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Forms.SharedConsent", b =>
                {
                    b.Navigation("AnswerSets");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Organisation", b =>
                {
                    b.Navigation("OrganisationPersons");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Person", b =>
                {
                    b.Navigation("PersonOrganisations");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Tenant", b =>
                {
                    b.Navigation("Organisations");
                });
#pragma warning restore 612, 618
        }
    }
}
