// <auto-generated />
using System;
using CO.CDP.OrganisationInformation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CO.CDP.OrganisationInformation.Persistence.Migrations
{
    [DbContext(typeof(OrganisationInformationContext))]
    [Migration("20240621115906_SnakeCaseNamingConvention")]
    partial class SnakeCaseNamingConvention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_name");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<string>("StreetAddress2")
                        .HasColumnType("text")
                        .HasColumnName("street_address2");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_guid");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_organisations_tenant_id");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.OrganisationPerson", b =>
                {
                    b.Property<int>("OrganisationId")
                        .HasColumnType("integer")
                        .HasColumnName("organisation_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scopes");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OrganisationId", "PersonId")
                        .HasName("pk_organisation_person");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_organisation_person_person_id");

                    b.ToTable("organisation_person", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserUrn")
                        .HasColumnType("text")
                        .HasColumnName("user_urn");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_email");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_persons_guid");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_guid");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_name");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.TenantPerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("PersonId", "TenantId")
                        .HasName("pk_tenant_person");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_person_tenant_id");

                    b.ToTable("tenant_person", (string)null);
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Organisation", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Tenant", "Tenant")
                        .WithMany("Organisations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisations_tenants_tenant_id");

                    b.OwnsOne("CO.CDP.OrganisationInformation.Persistence.Organisation+BuyerInformation", "BuyerInfo", b1 =>
                        {
                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("BuyerType")
                                .HasColumnType("text")
                                .HasColumnName("buyer_type");

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<int[]>("DevolvedRegulations")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("devolved_regulations");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("OrganisationId")
                                .HasName("pk_buyer_information");

                            b1.ToTable("buyer_information", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_buyer_information_organisations_id");
                        });

                    b.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+ContactPoint", "ContactPoints", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("organisation_id");

                            b1.Property<string>("Telephone")
                                .HasColumnType("text")
                                .HasColumnName("telephone");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Url")
                                .HasColumnType("text")
                                .HasColumnName("url");

                            b1.HasKey("Id")
                                .HasName("pk_contact_points");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_contact_points_organisation_id");

                            b1.ToTable("contact_points", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_contact_points_organisations_organisation_id");
                        });

                    b.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+Identifier", "Identifiers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("IdentifierId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("identifier_id");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("legal_name");

                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("organisation_id");

                            b1.Property<bool>("Primary")
                                .HasColumnType("boolean")
                                .HasColumnName("primary");

                            b1.Property<string>("Scheme")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scheme");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Uri")
                                .HasColumnType("text")
                                .HasColumnName("uri");

                            b1.HasKey("Id")
                                .HasName("pk_identifiers");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_identifiers_organisation_id");

                            b1.ToTable("identifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_identifiers_organisations_organisation_id");
                        });

                    b.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+OrganisationAddress", "Addresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AddressId")
                                .HasColumnType("integer")
                                .HasColumnName("address_id");

                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("organisation_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_organisation_address");

                            b1.HasIndex("AddressId")
                                .HasDatabaseName("ix_organisation_address_address_id");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_organisation_address_organisation_id");

                            b1.ToTable("organisation_address", (string)null);

                            b1.HasOne("CO.CDP.OrganisationInformation.Persistence.Address", "Address")
                                .WithMany()
                                .HasForeignKey("AddressId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_organisation_address_address_address_id");

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_organisation_address_organisations_organisation_id");

                            b1.Navigation("Address");
                        });

                    b.OwnsOne("CO.CDP.OrganisationInformation.Persistence.Organisation+SupplierInformation", "SupplierInfo", b1 =>
                        {
                            b1.Property<int>("OrganisationId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<bool>("CompletedEmailAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_email_address");

                            b1.Property<bool>("CompletedLegalForm")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_legal_form");

                            b1.Property<bool>("CompletedOperationType")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_operation_type");

                            b1.Property<bool>("CompletedPostalAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_postal_address");

                            b1.Property<bool>("CompletedQualification")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_qualification");

                            b1.Property<bool>("CompletedRegAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_reg_address");

                            b1.Property<bool>("CompletedTradeAssurance")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_trade_assurance");

                            b1.Property<bool>("CompletedVat")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_vat");

                            b1.Property<bool>("CompletedWebsiteAddress")
                                .HasColumnType("boolean")
                                .HasColumnName("completed_website_address");

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<int[]>("OperationTypes")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasColumnName("operation_types");

                            b1.Property<int?>("SupplierType")
                                .HasColumnType("integer")
                                .HasColumnName("supplier_type");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.HasKey("OrganisationId")
                                .HasName("pk_supplier_information");

                            b1.ToTable("supplier_information", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_supplier_information_organisations_id");

                            b1.OwnsOne("CO.CDP.OrganisationInformation.Persistence.Organisation+LegalForm", "LegalForm", b2 =>
                                {
                                    b2.Property<int>("SupplierInformationOrganisationId")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("CreatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.Property<string>("LawRegistered")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("law_registered");

                                    b2.Property<string>("RegisteredLegalForm")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("registered_legal_form");

                                    b2.Property<string>("RegisteredUnderAct2006")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("registered_under_act2006");

                                    b2.Property<DateTimeOffset>("RegistrationDate")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("registration_date");

                                    b2.Property<DateTimeOffset>("UpdatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.HasKey("SupplierInformationOrganisationId")
                                        .HasName("pk_legal_forms");

                                    b2.ToTable("legal_forms", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierInformationOrganisationId")
                                        .HasConstraintName("fk_legal_forms_supplier_information_id");
                                });

                            b1.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+Qualification", "Qualifications", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("AwardedByPersonOrBodyName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("awarded_by_person_or_body_name");

                                    b2.Property<DateTimeOffset>("CreatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.Property<DateTimeOffset>("DateAwarded")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("date_awarded");

                                    b2.Property<Guid>("Guid")
                                        .HasColumnType("uuid")
                                        .HasColumnName("guid");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.Property<int>("SupplierInformationOrganisationId")
                                        .HasColumnType("integer")
                                        .HasColumnName("supplier_information_organisation_id");

                                    b2.Property<DateTimeOffset>("UpdatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.HasKey("Id")
                                        .HasName("pk_qualifications");

                                    b2.HasIndex("Guid")
                                        .IsUnique()
                                        .HasDatabaseName("ix_qualifications_guid");

                                    b2.HasIndex("SupplierInformationOrganisationId")
                                        .HasDatabaseName("ix_qualifications_supplier_information_organisation_id");

                                    b2.ToTable("qualifications", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierInformationOrganisationId")
                                        .HasConstraintName("fk_qualifications_supplier_information_supplier_information_or");
                                });

                            b1.OwnsMany("CO.CDP.OrganisationInformation.Persistence.Organisation+TradeAssurance", "TradeAssurances", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("AwardedByPersonOrBodyName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("awarded_by_person_or_body_name");

                                    b2.Property<DateTimeOffset>("CreatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.Property<DateTimeOffset>("DateAwarded")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("date_awarded");

                                    b2.Property<Guid>("Guid")
                                        .HasColumnType("uuid")
                                        .HasColumnName("guid");

                                    b2.Property<string>("ReferenceNumber")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("reference_number");

                                    b2.Property<int>("SupplierInformationOrganisationId")
                                        .HasColumnType("integer")
                                        .HasColumnName("supplier_information_organisation_id");

                                    b2.Property<DateTimeOffset>("UpdatedOn")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("updated_on")
                                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                                    b2.HasKey("Id")
                                        .HasName("pk_trade_assurances");

                                    b2.HasIndex("Guid")
                                        .IsUnique()
                                        .HasDatabaseName("ix_trade_assurances_guid");

                                    b2.HasIndex("SupplierInformationOrganisationId")
                                        .HasDatabaseName("ix_trade_assurances_supplier_information_organisation_id");

                                    b2.ToTable("trade_assurances", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SupplierInformationOrganisationId")
                                        .HasConstraintName("fk_trade_assurances_supplier_information_supplier_information_");
                                });

                            b1.Navigation("LegalForm");

                            b1.Navigation("Qualifications");

                            b1.Navigation("TradeAssurances");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("BuyerInfo");

                    b.Navigation("ContactPoints");

                    b.Navigation("Identifiers");

                    b.Navigation("SupplierInfo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.OrganisationPerson", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Organisation", "Organisation")
                        .WithMany("OrganisationPersons")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_person_organisations_organisation_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Person", "Person")
                        .WithMany("PersonOrganisations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organisation_person_persons_person_id");

                    b.Navigation("Organisation");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.TenantPerson", b =>
                {
                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_person_persons_person_id");

                    b.HasOne("CO.CDP.OrganisationInformation.Persistence.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_person_tenants_tenant_id");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Organisation", b =>
                {
                    b.Navigation("OrganisationPersons");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Person", b =>
                {
                    b.Navigation("PersonOrganisations");
                });

            modelBuilder.Entity("CO.CDP.OrganisationInformation.Persistence.Tenant", b =>
                {
                    b.Navigation("Organisations");
                });
#pragma warning restore 612, 618
        }
    }
}
