{
 "title": "OpenSearch Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "client_id", "label": "ClientId", "query": "GRAFANA_CLOUDWATCH_ACCOUNT_ID" },
   { "name": "region", "label": "Region", "query": "eu-west-2" },
   {
    "name": "domain",
    "label": "Domain",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Green",
     "metricName": "ClusterStatus.green",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Yellow",
     "metricName": "ClusterStatus.yellow",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Red",
     "metricName": "ClusterStatus.red",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Master Reachable",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Master reachable",
     "metricName": "MasterReachableFromNode",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "CPU utilization",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "JVM Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "JVM memory pressure",
     "metricName": "JVMMemoryPressure",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expression": "$A/1024*2", "type": "math" }
   ]
  },
  {
   "title": "Cluster Writes Blocked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Cluster writes blocked",
     "metricName": "ClusterIndexWritesBlocked",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Search latency",
     "metricName": "SearchLatency",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Indexing Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Indexing latency",
     "metricName": "IndexingLatency",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Search Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Search rate",
     "metricName": "SearchRate",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Indexing Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Indexing rate",
     "metricName": "IndexingRate",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "5xx Requests",
     "metricName": "5xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "4xx Requests",
     "metricName": "4xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "HTTP Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "2xx",
     "metricName": "2xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "3xx",
     "metricName": "3xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "4xx",
     "metricName": "4xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "5xx",
     "metricName": "5xx",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Total nodes",
     "metricName": "Nodes",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Searchable Documents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Searchable docs",
     "metricName": "SearchableDocuments",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Deleted Documents",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Deleted docs",
     "metricName": "DeletedDocuments",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Master CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Master CPU",
     "metricName": "MasterCPUUtilization",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Master JVM Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Master JVM",
     "metricName": "MasterJVMMemoryPressure",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "OpenSearch Dashboards Healthy Nodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Healthy dashboards nodes",
     "metricName": "OpenSearchDashboardsHealthyNodes",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Automated Snapshot Failure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Snapshot failure",
     "metricName": "AutomatedSnapshotFailure",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Invalid Host Header Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ClientId": "$client_id", "DomainName": "$domain" },
     "label": "Invalid host header",
     "metricName": "InvalidHostHeaderRequests",
     "namespace": "AWS/ES",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  }
 ]
}