services:
  fluentbit:
    build: .
    image: cabinetoffice/cdp-fluentbit:latest
    ports:
      - "2020:2020"
      - "2021:2021"
#    volumes:
#      - fluentbit-configs:/fluent-bit/etc
#
#volumes:
#  fluentbit-configs:
#    driver: local
