{
 "title": "Cloud-Beaver",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Last 10 Errors",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like \"err\" or @message like \"ERR\" or @message like \"Err\"\n| sort @timestamp desc\n| limit 5",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/cloud-beaver:*",
       "name": "/ecs/cloud-beaver"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Last 10 Warning",
   "type": "logs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| filter @message like \"warn\" or @message like \"WARN\" or @message like \"Warn\"\n| sort @timestamp desc\n| limit 5",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/cloud-beaver:*",
       "name": "/ecs/cloud-beaver"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "All",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expression": "fields @timestamp, @message \n| sort @timestamp desc",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/cloud-beaver:*",
       "name": "/ecs/cloud-beaver"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}