{
 "title": "Grafana",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Last 5 Errors",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse @message \"level=* msg=\\\"*\\\"\" as log_level, log_message, more\n| filter log_level like \"err\"\n| sort @timestamp desc\n| limit 5",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/grafana:*",
       "name": "/ecs/grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Last 10 Warning",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expression": "fields @timestamp, @message\n| parse @message \"level=* msg=\\\"*\\\"\" as log_level, log_message, more\n| filter log_level like \"warn\"\n| sort @timestamp desc\n| limit 5",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/grafana:*",
       "name": "/ecs/grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "All",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "fields @timestamp, @message \n| sort @timestamp desc",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:/ecs/grafana:*",
       "name": "/ecs/grafana"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}