{
 "title": "ALB Errors & Connections - External - TOOLS",
 "tags": [
  "traffic",
  "internal",
  "external"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "external_loadbalancer",
    "label": "External ALB",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "ELB 4XX (External)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$external_loadbalancer" },
     "label": "external",
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_ELB_4XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$external_loadbalancer" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_ELB_4XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$external_loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target 4XX (External)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$external_loadbalancer" },
     "label": "external",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "HTTPCode_Target_4XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$external_loadbalancer" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(HTTPCode_Target_4XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$external_loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "New Connections (External)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$external_loadbalancer" },
     "label": "external",
     "metricName": "NewConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "NewConnectionCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$external_loadbalancer" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(NewConnectionCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$external_loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Active Connections (External)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$external_loadbalancer" },
     "label": "external",
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "AVG",
       "parameters": [
        { "name": "ActiveConnectionCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$external_loadbalancer" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT AVG(ActiveConnectionCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = \"$external_loadbalancer\"",
     "statistic": "Sum"
    }
   ]
  }
 ]
}