{
 "title": "External Traffic (WAF)",
 "tags": [
  "traffic",
  "external",
  "waf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "web_acl",
    "label": "Web ACL",
    "query": {}
   },
   {
    "name": "waf_log_group",
    "label": "WAF Log Group",
    "query": "aws-waf-logs-cdp-sirsi, aws-waf-logs-cdp-sirsi-php, aws-waf-logs-cdp-sirsi-fts, aws-waf-logs-cdp-sirsi-tools"
   }
  ]
 },
 "panels": [
  {
   "title": "WAF Requests by Action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "WebACL": "$web_acl", "Region": "eu-west-2", "Rule": "ALL" },
     "label": "Allowed",
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "AllowedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "type": "operator", "property": { "name": "Rule", "type": "string" }, "operator": { "name": "=", "value": "ALL" } },
        { "type": "operator", "property": { "name": "Region", "type": "string" }, "operator": { "name": "=", "value": "eu-west-2" } },
        { "operator": { "name": "=", "value": "$web_acl" }, "property": { "name": "WebACL", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(AllowedRequests) FROM \"AWS/WAFV2\" WHERE Rule = 'ALL' AND Region = 'eu-west-2' AND WebACL = '$web_acl'",
     "statistic": "Sum"
    },
    {
     "dimensions": { "WebACL": "$web_acl", "Region": "eu-west-2", "Rule": "ALL" },
     "label": "Blocked",
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "BlockedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "type": "operator", "property": { "name": "Rule", "type": "string" }, "operator": { "name": "=", "value": "ALL" } },
        { "type": "operator", "property": { "name": "Region", "type": "string" }, "operator": { "name": "=", "value": "eu-west-2" } },
        { "operator": { "name": "=", "value": "$web_acl" }, "property": { "name": "WebACL", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(BlockedRequests) FROM \"AWS/WAFV2\" WHERE Rule = 'ALL' AND Region = 'eu-west-2' AND WebACL = '$web_acl'",
     "statistic": "Sum"
    },
    {
     "dimensions": { "WebACL": "$web_acl", "Region": "eu-west-2", "Rule": "ALL" },
     "label": "Counted",
     "metricName": "CountedRequests",
     "namespace": "AWS/WAFV2",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/WAFV2", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "CountedRequests", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "type": "operator", "property": { "name": "Rule", "type": "string" }, "operator": { "name": "=", "value": "ALL" } },
        { "type": "operator", "property": { "name": "Region", "type": "string" }, "operator": { "name": "=", "value": "eu-west-2" } },
        { "operator": { "name": "=", "value": "$web_acl" }, "property": { "name": "WebACL", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(CountedRequests) FROM \"AWS/WAFV2\" WHERE Rule = 'ALL' AND Region = 'eu-west-2' AND WebACL = '$web_acl'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Top Client IPs (all actions)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expression": "fields httpRequest.clientIp as ClientIP | stats count() as Requests by ClientIP | sort Requests desc | limit 20",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:$waf_log_group:*",
       "name": "$waf_log_group"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Countries (all actions)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expression": "fields httpRequest.country as Country | stats count() as Requests by Country | sort Requests desc | limit 20",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:$waf_log_group:*",
       "name": "$waf_log_group"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top URIs (all actions)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expression": "fields httpRequest.uri as URI | stats count() as Requests by URI | sort Requests desc | limit 20",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:$waf_log_group:*",
       "name": "$waf_log_group"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Top Blocked Rules",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expression": "fields action, labels.0.name as Rule | filter action = \"BLOCK\" | stats count() as Blocked by Rule | sort Blocked desc | limit 20",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:$waf_log_group:*",
       "name": "$waf_log_group"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Recent Blocked Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expression": "fields @timestamp, action as Action, labels.0.name as Rule, httpRequest.clientIp as ClientIP, httpRequest.country as Country, httpRequest.httpMethod as Method, httpRequest.uri as URI | filter action = \"BLOCK\" | sort @timestamp desc | limit 50",
     "logGroups": [
      {
       "accountId": "GRAFANA_CLOUDWATCH_ACCOUNT_ID",
       "arn": "arn:aws:logs:eu-west-2:GRAFANA_CLOUDWATCH_ACCOUNT_ID:log-group:$waf_log_group:*",
       "name": "$waf_log_group"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}