version: '3.8'

services:
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e2e_tests
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - cdp-sirsi

networks:
  cdp-sirsi:
    external: true
