// <auto-generated />
using CO.CDP.EntityVerification.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CO.CDP.EntityVerification.Migrations
{
    [DbContext(typeof(EntityValidationContext))]
    [Migration("20240712100055_CreateEVSchema")]
    partial class CreateEVSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entity_validation")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CO.CDP.EntityVerification.Persistence.Ppon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PponId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ppon_id");

                    b.HasKey("Id")
                        .HasName("pk_ppon");

                    b.HasIndex("PponId")
                        .IsUnique()
                        .HasDatabaseName("ix_ppon_ppon_id");

                    b.ToTable("ppon", "entity_validation");
                });
#pragma warning restore 612, 618
        }
    }
}
