// <auto-generated />
using System;
using CO.CDP.EntityVerification.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CO.CDP.EntityVerification.Migrations
{
    [DbContext(typeof(EntityVerificationContext))]
    partial class EntityVerificationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entity_verification")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CO.CDP.EntityVerification.Persistence.Ppon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdentifierId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_ppons");

                    b.HasIndex("IdentifierId")
                        .IsUnique()
                        .HasDatabaseName("ix_ppons_identifier_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_ppons_name");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_ppons_organisation_id");

                    b.ToTable("ppons", "entity_verification");
                });

            modelBuilder.Entity("CO.CDP.EntityVerification.Persistence.Ppon", b =>
                {
                    b.OwnsMany("CO.CDP.EntityVerification.Persistence.Identifier", "Identifiers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTimeOffset>("CreatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("IdentifierId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("identifier_id");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("legal_name");

                            b1.Property<string>("Scheme")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scheme");

                            b1.Property<DateTimeOffset>("UpdatedOn")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Uri")
                                .HasColumnType("text")
                                .HasColumnName("uri");

                            b1.Property<int>("ppon_id")
                                .HasColumnType("integer")
                                .HasColumnName("ppon_id");

                            b1.HasKey("Id")
                                .HasName("pk_identifiers");

                            b1.HasIndex("IdentifierId")
                                .HasDatabaseName("ix_identifiers_identifier_id");

                            b1.HasIndex("Scheme")
                                .HasDatabaseName("ix_identifiers_scheme");

                            b1.HasIndex("ppon_id")
                                .HasDatabaseName("ix_identifiers_ppon_id");

                            b1.ToTable("identifiers", "entity_verification");

                            b1.WithOwner()
                                .HasForeignKey("ppon_id")
                                .HasConstraintName("fk_identifiers_ppons_ppon_id");
                        });

                    b.Navigation("Identifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
