// <auto-generated />
using System;
using CO.CDP.EntityVerification.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CO.CDP.EntityVerification.Migrations
{
    [DbContext(typeof(EntityVerificationContext))]
    partial class EntityVerificationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("entity_verification")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CO.CDP.EntityVerification.Persistence.Identifier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheme");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_identifier");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_identifier_id");

                    b.ToTable("identifier", "entity_verification");
                });

            modelBuilder.Entity("CO.CDP.EntityVerification.Persistence.Ppon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdentifierId")
                        .HasColumnType("integer")
                        .HasColumnName("identifier_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PponId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ppon_id");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_ppon");

                    b.HasIndex("PponId")
                        .IsUnique()
                        .HasDatabaseName("ix_ppon_ppon_id");

                    b.ToTable("ppon", "entity_verification");
                });

            modelBuilder.Entity("CO.CDP.EntityVerification.Persistence.Identifier", b =>
                {
                    b.HasOne("CO.CDP.EntityVerification.Persistence.Ppon", "Ppon")
                        .WithOne("Identifier")
                        .HasForeignKey("CO.CDP.EntityVerification.Persistence.Identifier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identifier_ppon_id");

                    b.Navigation("Ppon");
                });

            modelBuilder.Entity("CO.CDP.EntityVerification.Persistence.Ppon", b =>
                {
                    b.Navigation("Identifier")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
