= Software Architecture

== Container view

The diagram below focuses on high level responsibilities and technology choices within the Central Digital Platform system.

.Container View of the Central Digital Platform system
image::diagrams/structurizr-1-CDP-2-ContainerView.svg[Container View of the Central Digital Platform system]

.Legend
image::diagrams/structurizr-1-CDP-2-ContainerView-key.svg[Legend]

Most of the services that were implemented have been defined as part of the High Level Design
(`TPP Identity and Organisation Information Services HLD v0.1.docx`) that the team was given to follow when they started.

A number of Web APIs is designed to be seen as independent externally, but internally shares the database.
The entity verification services is one exception here as it is explicitly designed to be isolated from other services.

== Personas

There are two main public personas that interact with the system: suppliers and buyers.

=== Supplier

Suppliers offer their services to government organisations.
They use SIRSI to sign up their organisation on the platform, fill out their profile (supplier information),
manage users and API keys.

=== Buyer

Buyers are government organisation that buy services from suppliers.
They use SIRSI to sign up their organisation on the platform.

== External services

=== GOV.UK One Login

https://www.sign-in.service.gov.uk/[GOV.UK One Login] is used as a single sign-on solution shared between all
the CDP services to provide seamless navigation experience between them.


=== GOV.UK Notify

https://www.notifications.service.gov.uk/[GOV.UK Notify] is used to send out email notifications to users.

== Applications and services

=== Organisation Web Application

The Organisation web application is where buyers and suppliers sign up and manage their organisations.
This is where suppliers provide the supplier information that is later used in the procurement process.

.Organisation web application components
image::diagrams/structurizr-1-CDP-3-OrganisationApp-Components.svg[Organisation web application components]

The web application implements the User Interface with the https://design-system.service.gov.uk/[GOV.UK Design system].
It calls other services (Web APIs) to perform actual work.

=== Authority

The **Authority** service provides an OpenID based authentication for the Web APIs.
It's used to exchange the One Login token to our own one. This is to make the token valid for longer.
One Login token is only valid for three minutes, while the Authority token is valid for one hour.

The **Authority** service is one of the few services that were not part of the High Level Design.
Originally, Web APIs were suppose to be authenticated with One Login tokens.
This turned out not be be practical due to their short-lived nature.

.Authority service components
image::diagrams/structurizr-1-CDP-3-Authority-Components.svg[Authority service components]

=== Tenant

.Tenant service components
image::diagrams/structurizr-1-CDP-4-TenantApi-Components.svg[Tenant service components]

=== Person

.Person service components
image::diagrams/structurizr-1-CDP-5-PersonApi-Components.svg[Person service components]

=== Organisation

.Organisation service components
image::diagrams/structurizr-1-CDP-6-OrganisationApi-Components.svg[Organisation service components]

=== Forms

.Forms service components
image::diagrams/structurizr-1-CDP-7-FormsApi-Components.svg[Forms service components]

=== Data sharing

.Data sharing service components
image::diagrams/structurizr-1-CDP-8-DataSharingApi-Components.svg[Data sharing service components]

=== Entity verification

.Entity verification service components
image::diagrams/structurizr-1-CDP-9-EntityVerification-Components.svg[Entity verification service components]

== Logging

The applications log via Serilog, routed to AWS CloudWatch. See `Libraries\CO.CDP.AwsServices\CloudWatchExtensions.cs`

See also https://github.com/serilog/serilog-formatting-compact

Log messages have the following properties, delivered as a JSON payload:

_(Note that not all properties are listed here - not all log messages contain all properties, but these are some common ones.)_

*@t*
Timestamp that the log entry was recorded

Example:
`2025-02-03T13:56:30.1964115Z`

*@m*
Message from the application

Example:
`Executed endpoint '\"/Organisation/OrganisationSelection\"'`

or

"Failed to call Companies House API.",

*@i*
Event ID. Not something we use at the moment but could be considered in future.

Example:
`99874f2b`

*@tr*
Trace ID - a unique identifier for an end to end operation within the service. Stays the same across all services handling the request.

Example:
`4d0370e686fd28253bdc1f22ea878049`

*@sp*
Span ID - a unique identifier for operations within an individual application. Works in concert with Trace ID above.

Example:
`b52b7ecfe8fcd1b5`

*@x*
Exception details

Example:

```
"@x": "CDP_COMPANIES_HOUSE_API_ERROR: Inner exception: CO.CDP.OrganisationApp.Logging.CdpExceptionLogging: Failed to call Companies House API for company number: S2.\n ---> Flurl.Http.FlurlHttpException: Call failed with status code 500 (Internal Server Error): GET https://api.company-information.service.gov.uk/company/S2/registered-office-address\n   at Flurl.Http.FlurlClient.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)\n   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n   at Flurl.Http.FlurlClient.SendAsync(IFlurlRequest request, HttpCompletionOption completionOption, CancellationToken cancellationToken)\n   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)\n   at CO.CDP.OrganisationApp.ThirdPartyApiClients.CompaniesHouse.CompaniesHouseApi.GetRegisteredAddress(String companyNumber) in /src/Frontend/CO.CDP.OrganisationApp/ThirdPartyApiClients/CompaniesHouse/CompaniesHouseApi.cs:line 21\n   --- End of inner exception stack trace ---"
```

*EndpointName*
Identifies the endpoint which was called. In Razor pages this would be the PageName. Does not match the URL - see `RequestPath` below.

Example:
`/Organisation/OrganisationSelection`

*SourceContext*
Name of the class which generated the log entry

Example:
`Microsoft.AspNetCore.Routing.EndpointMiddleware`

*RequestId*
Uniquely identifies an http request. Restricted to the current application (As opposed to Trace ID above)

Example:
`0HNA4932U79QL:00000004`

*RequestPath*
The URL that is being requested.

Example:
`/organisation-selection`

*ConnectionId*
Uniquely identifies the http connection.

Example:
`0HNA4932U79QL`

*Version*
The version of the running application. Corresponds to the Git tag.

Example:
`1.0.30`
