CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240314110111_CreateTenants') THEN
    CREATE TABLE "Tenants" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Guid" uuid NOT NULL,
        "Name" text NOT NULL,
        "ContactInfo_Email" text NOT NULL,
        "ContactInfo_Phone" text NOT NULL,
        CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240314110111_CreateTenants') THEN
    CREATE UNIQUE INDEX "IX_Tenants_Guid" ON "Tenants" ("Guid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240314110111_CreateTenants') THEN
    CREATE UNIQUE INDEX "IX_Tenants_Name" ON "Tenants" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240314110111_CreateTenants') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240314110111_CreateTenants', '8.0.3');
    END IF;
END $EF$;
COMMIT;

