name: Grafana Terraform

on:
  push:
    branches: [main]
    paths:
      - "terragrunt/tools/grafana/**"
      - ".github/workflows/grafana-terraform.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  apply-development:
    uses: ./.github/workflows/grafana-terraform-apply.yml
    with:
      environment: development
      account_id: "471112892058"
      base_domain: supplier-information.find-tender.service.gov.uk

  apply-staging:
    needs: apply-development
    uses: ./.github/workflows/grafana-terraform-apply.yml
    with:
      environment: staging
      account_id: "905418042182"
      base_domain: supplier-information.find-tender.service.gov.uk

  apply-integration:
    needs: apply-staging
    uses: ./.github/workflows/grafana-terraform-apply.yml
    with:
      environment: integration
      account_id: "767397666448"
      base_domain: supplier-information.find-tender.service.gov.uk

  apply-production:
    needs: apply-integration
    uses: ./.github/workflows/grafana-terraform-apply.yml
    with:
      environment: production
      account_id: "471112843276"
      base_domain: supplier-information.find-tender.service.gov.uk
