name: Build

on:
  pull_request:
    branches: [main]

jobs:
  test:

    runs-on: ubuntu-latest
    name: Tests
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Build
        run: make build OpenAPI
      - name: Test
        run: make test TEST_OPTIONS="--logger trx --results-directory 'TestResults-${{ matrix.dotnet-version }}'"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-dotnet-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}
      - name: Upload OpenAPI contracts
        uses: actions/upload-artifact@v4
        with:
          name: OpenAPI
          path: OpenAPI

  docker:
    runs-on: ubuntu-latest
    name: Build containers
    env:
      CDP_ORGANISATION_APP_PORT: 8888
      CDP_TENANT_PORT: 8811
      CDP_ORGANISATION_PORT: 8822
      CDP_PERSON_PORT: 8833
      CDP_FORMS_PORT: 8844
      CDP_DATA_SHARING_PORT: 8855
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build-docker
      - name: Start services
        run: make up
      - name: Stop services
        run: make down

  document:
    runs-on: ubuntu-latest
    name: Publish documentation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: cd docs && make build
